'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');
const { execFileSync } = require('child_process');

const WRAPPER_PATH = path.join(os.homedir(), '.kitsune-ollama.sh');

// All agents launchable via `ollama launch <name>`
const OLLAMA_AGENTS = [
  { name: 'claude',    label: 'Claude Code'  },
  { name: 'opencode',  label: 'OpenCode'     },
  { name: 'codex',     label: 'Codex'        },
  { name: 'codex-app', label: 'Codex App'    },
  { name: 'openclaw',  label: 'OpenClaw'     },
  { name: 'hermes',    label: 'Hermes Agent' },
];

function isOllamaInstalled() {
  try { execFileSync('ollama', ['--version'], { stdio: 'ignore' }); return true; }
  catch { return false; }
}

function generateWrapperScript(defaultModel = 'qwen3.5') {
  const fns = OLLAMA_AGENTS.map(({ name, label }) => [
    `# ${label}`,
    `ok-${name}() {`,
    `  local model="\${1:-${defaultModel}}"`,
    `  KITSUNE_AGENT=ollama-${name} ollama launch ${name} --model "$model" 2>&1 | kitsune`,
    `}`,
  ].join('\n')).join('\n\n');

  return [
    '# Kitsune × Ollama — shell wrappers',
    '# Generated by: kitsune install --ollama',
    '# Usage: ok-<agent> [model]   e.g. ok-claude qwen3.5',
    '',
    fns,
    '',
  ].join('\n');
}

/**
 * Writes ~/.kitsune-ollama.sh with wrapper functions for all ollama agents.
 */
async function installOllama() {
  if (!isOllamaInstalled()) {
    console.log('⚠ ollama not found in PATH — install from https://ollama.com first');
    return;
  }

  fs.writeFileSync(WRAPPER_PATH, generateWrapperScript());
  console.log(`✓ Wrote Ollama wrappers to ${WRAPPER_PATH}`);
  console.log('');
  console.log('Add this line to your ~/.zshrc or ~/.bashrc:');
  console.log(`  source ${WRAPPER_PATH}`);
  console.log('');
  console.log('Then use any of these:');
  for (const { name, label } of OLLAMA_AGENTS) {
    console.log(`  ok-${name.padEnd(10)} # ${label}`);
  }
  console.log('');
  console.log('Pass a model as the first arg (default: qwen3.5):');
  console.log('  ok-claude llama3.1');
}

/**
 * Removes ~/.kitsune-ollama.sh.
 */
async function uninstallOllama() {
  if (!fs.existsSync(WRAPPER_PATH)) {
    console.log(`⊘ ${WRAPPER_PATH} not found — nothing to remove`);
    return;
  }
  fs.rmSync(WRAPPER_PATH);
  console.log(`✓ Removed ${WRAPPER_PATH}`);
  console.log('Remove the source line from your ~/.zshrc or ~/.bashrc manually.');
}

module.exports = { installOllama, uninstallOllama, isOllamaInstalled, generateWrapperScript, OLLAMA_AGENTS };
