const fs = require('fs');
const path = require('path');
const os = require('os');

function findOpencodeConfigDir() {
  const candidates = [
    path.join(os.homedir(), '.opencode'),
    path.join(os.homedir(), '.config', 'opencode'),
  ];
  return candidates.find(d => fs.existsSync(d)) || null;
}

const PLUGIN_CONTENT = `// kitsune-plugin.js — auto-generated by kitsune installer
// Pipes session output through kitsune after each session ends.
import { spawn } from 'child_process';

export default {
  name: 'kitsune',
  hooks: {
    afterSession({ output }) {
      const text = (output || '').slice(-2000);
      const kitsune = spawn('kitsune', [], { stdio: ['pipe', 'inherit', 'inherit'] });
      kitsune.stdin.write(text);
      kitsune.stdin.end();
    },
  },
};
`;

const MANUAL_INSTRUCTIONS = `
Kitsune opencode integration — manual setup
─────────────────────────────────────────────
opencode config directory not found. To integrate manually:

1. Find your opencode plugin directory (check opencode docs or opencode --help)
2. Create a file named kitsune-plugin.js there
3. The plugin should pipe session output through: spawn('kitsune', [], { stdio: ['pipe', 'inherit', 'inherit'] })
4. Register it in your opencode config if required.
`;

async function installOpencode({ dryRun } = {}) {
  if (dryRun) {
    console.log('(dry run) Would install opencode kitsune plugin');
    return;
  }

  const configDir = findOpencodeConfigDir();
  if (!configDir) {
    console.log(MANUAL_INSTRUCTIONS);
    return;
  }

  const pluginsDir = path.join(configDir, 'plugins');
  const pluginPath = path.join(pluginsDir, 'kitsune-plugin.js');

  fs.mkdirSync(pluginsDir, { recursive: true });

  if (!fs.existsSync(pluginPath)) {
    fs.writeFileSync(pluginPath, PLUGIN_CONTENT);
    console.log(`✓ opencode kitsune plugin written to ${pluginPath}`);
    console.log('  (register it in your opencode config if required)');
  } else {
    console.log(`✓ opencode plugin already exists at ${pluginPath} — skipping`);
  }
}

async function uninstallOpencode() {
  const configDir = findOpencodeConfigDir();
  if (!configDir) {
    console.log('⊘ opencode config directory not found — nothing to remove');
    return;
  }
  const pluginPath = path.join(configDir, 'plugins', 'kitsune-plugin.js');
  if (!fs.existsSync(pluginPath)) {
    console.log(`⊘ opencode plugin not found at ${pluginPath} — nothing to remove`);
    return;
  }
  fs.rmSync(pluginPath);
  console.log(`✓ Removed opencode kitsune plugin at ${pluginPath}`);
}

module.exports = { installOpencode, uninstallOpencode };
